autoscout24_features = {"Fahrerairbag", "ABS", "Servolenkung", "Beifahrerairbag", "Wegfahrsperre",
                        "Elektr. Fensterheber", "Seitenairbag", "Zentralverriegelung",
                        "Elektrische Seitenspiegel", "Radio", "Klimaanlage", "Getönte Scheiben", "ESP",
                        "teilb. Rücksitzbank", "Nebelscheinwerfer", "Isofix", "CD", "Alufelgen", "Stahlfelgen",
                        "Traktionskontrolle", "Bordcomputer", "Zentralverriegelung mit Funkfernbedienung",
                        "Lederlenkrad", "Armlehne", "Reserverad", "Kopfairbag", "Klimaautomatik", "Dachreling",
                        "Winterreifen", "Airbag hinten", "Multifunktionslenkrad", "Allwetterreifen",
                        "Katalysator", "Tempomat", "Sitzheizung", "Anhängerkupplung", "Sportsitze", "MP3",
                        "Regensensor", "Sommerreifen", "Notrad", "Bluetooth", "Einparkhilfe",
                        "Innenspiegel automatisch abblendend", "Gepäckraumabtrennung",
                        "Einparkhilfe Sensoren hinten", "E10-geeignet", "Lordosenstütze", "Schiebedach",
                        "Alarmanlage", "Lichtsensor", "Soundsystem", "USB", "Umklappbarer Beifahrersitz",
                        "Schlüssellose Zentralverriegelung", "Beheizbare Frontscheibe", "Raucherpaket",
                        "Spoiler", "Notbremsassistent", "Elektrische Sitze", "Freisprecheinrichtung",
                        "Scheinwerferreinigung", "Skisack", "Lederausstattung", "Sportfahrwerk",
                        "Navigationssystem", "Xenonscheinwerfer", "Pannenkit", "Reifendruckkontrollsystem",
                        "Panoramadach", "2-Zonen-Klimaautomatik", "Winterpaket", "Tagfahrlicht", "DAB-Radio",
                        "Berganfahrassistent", "Sportpaket", "Geschwindigkeits-begrenzungsanlage",
                        "Standheizung", "Einparkhilfe Sensoren vorne", "Kurvenlicht", "Allrad",
                        "Ambientebeleuchtung", "Einparkhilfe Kamera", "Schiebetür rechts", "Android Auto",
                        "Elektronische Parkbremse", "Touchscreen", "Elektrische Heckklappe",
                        "Musikstreaming integriert", "Luftfederung", "LED-Scheinwerfer", "Schiebetür links",
                        "Sprachsteuerung", "Windschott(für Cabrio)", "Beheizbares Lenkrad", "Apple CarPlay",
                        "LED-Tagfahrlicht", "4-Zonen-Klimaautomatik", "Tuning", "Bi-Xenon Scheinwerfer",
                        "Blendfreies Fernlicht", "Fernlichtassistent", "Verkehrszeichenerkennung",
                        "Batteriezertifikat", "Start/Stop-Automatik", "Schiebetür", "Notrufsystem",
                        "Abstandswarner", "Sitzheizung hinten", "3-Zonen-Klimaautomatik",
                        "W-Lan / Wifi Hotspot", "Sitzbelüftung", "Markise", "Rechtslenker",
                        "Volldigitales Kombiinstrument", "Doppelkabine", "Massagesitze",
                        "Voll-LED Scheinwerfer", "Behindertengerecht", "Nachtsicht-Assistent",
                        "Abstandstempomat", "Induktionsladen für Smartphones", "Totwinkel-Assistent",
                        "Einparkhilfe selbstlenkendes System", "Schaltwippen", "Spurhalteassistent", "TV"}

autoscout24_car_filters = [
    {'Alfa Romeo': '6'}, {'Aston Martin': '8'}, {'Audi': '9'}, {'Bentley': '11'},
    {'BMW': '13'}, {'Alpina': '14'}, {'Bugatti': '15'}, {'Buick': '16'},
    {'Cadillac': '17'}, {'Chevrolet': '19'}, {'Chrysler': '20'}, {'Citroen': '21'},
    {'Daewoo': '22'}, {'Daihatsu': '23'}, {'Ferrari': '27'}, {'Fiat': '28'},
    {'Ford': '29'}, {'Honda': '31'}, {'Hyundai': '33'}, {'Isuzu': '35'},
    {'Jaguar': '37'}, {'Jeep': '38'}, {'Kia': '39'}, {'Lada': '40'},
    {'Lamborghini': '41'}, {'Lancia': '42'}, {'Lexus': '43'}, {'Lotus': '44'},
    {'Maserati': '45'}, {'Mazda': '46'}, {'Mercedes-Benz': '47'}, {'MG': '48'},
    {'Mitsubishi': '50'}, {'Morgan': '51'}, {'Nissan': '52'}, {'Oldsmobile': '53'},
    {'Opel': '54'}, {'Peugeot': '55'}, {'Pontiac': '56'}, {'Porsche': '57'},
    {'Renault': '60'}, {'Rolls-Royce': '61'}, {'Rover': '62'}, {'Saab': '63'},
    {'SEAT': '64'}, {'Skoda': '65'}, {'SsangYong': '66'}, {'Subaru': '67'},
    {'Suzuki': '68'}, {'Toyota': '70'}, {'TVR': '71'}, {'Volvo': '73'},
    {'Volkswagen': '74'}, {'Triumph': '2120'}, {'Dodge': '2152'}, {'GMC': '2153'},
    {'smart': '15525'}, {'Land Rover': '15641'}, {'MINI': '16338'},
    {'Maybach': '16348'}, {'Infiniti': '16355'}, {'Dacia': '16360'},
    {'Tesla': '51520'}, {'McLaren': '51519'}, {'Polestar': '51817'},
    {'Genesis': '51885'}, {'Cupra': '51802'}
]

mobile_features = {"ABS", "Tuner/Radio", "Servolenkung", "Elektr. Wegfahrsperre", "Zentralverriegelung",
                   "Elektr. Fensterheber", "Frontantrieb", "Elektr. Seitenspiegel", "Leichtmetallfelgen",
                   "Isofix", "CD-Spieler", "ESP", "Nebelscheinwerfer", "Nichtraucher-Fahrzeug",
                   "Traktionskontrolle", "Lederlenkrad", "Bordcomputer", "Winterreifen", "Reserverad",
                   "Stahlfelgen", "Allwetterreifen", "Armlehne", "Anhängerkupplung fest", "Sommerreifen",
                   "Bluetooth", "Sitzheizung", "Tempomat", "Scheckheftgepflegt", "Lordosenstütze",
                   "Multifunktionslenkrad", "USB", "Sportsitze", "Dachreling", "Freisprecheinrichtung",
                   "Gepäckraumabtrennung", "Regensensor", "Notrad", "Alarmanlage", "Soundsystem",
                   "Schiebedach", "Innenspiegel autom. abblendend", "Raucherpaket",
                   "Schlüssellose Zentralverriegelung (Keyless)", "Lichtsensor", "Pannenkit",
                   "Navigationssystem", "Partikelfilter", "Beheizbare Frontscheibe",
                   "Abgedunkelte Scheiben", "Tagfahrlicht", "Elektr. Sitzeinstellung", "Radio DAB",
                   "Anhängerkupplung abnehmbar", "Panorama-Dach", "Scheinwerferreinigung",
                   "Xenonscheinwerfer", "Umklappbarer Beifahrersitz", "Reifendruckkontrolle",
                   "Winterpaket", "Heckantrieb", "Garantie", "Kurvenlicht", "Geschwindigkeitsbegrenzer",
                   "Berganfahrassistent", "Notbremsassistent", "Standheizung", "Sportfahrwerk",
                   "Sportpaket", "LED-Scheinwerfer", "Touchscreen", "Allradantrieb",
                   "Ambiente-Beleuchtung", "Apple CarPlay", "Android Auto", "Blendfreies Fernlicht",
                   "LED-Tagfahrlicht", "Isofix Beifahrersitz", "Elektr. Heckklappe", "WLAN / Wifi Hotspot",
                   "Musikstreaming integriert", "Sprachsteuerung", "Elektr. Seitenspiegel anklappbar",
                   "Skisack", "Abstandswarner", "Bi-Xenon Scheinwerfer", "Multi-CD-Wechsler",
                   "Induktionsladen für Smartphones", "Start/Stopp-Automatik", "Totwinkel-Assistent",
                   "Faltdach", "Spurhalteassistent", "Abstandstempomat", "Müdigkeitswarner",
                   "Sitzheizung hinten", "Adaptives Kurvenlicht", "Luftfederung", "Fernlichtassistent",
                   "Laserlicht", "Verkehrszeichenerkennung", "Schaltwippen",
                   "Volldigitales Kombiinstrument", "Sitzbelüftung", "Beheizbares Lenkrad",
                   "Navigationsvorbereitung", "Ausparkassistent", "Massagesitze", "Inspektion neu", "Taxi",
                   "Notrufsystem", "TV", "Elektr. Sitzeinstellung mit Memory-Funktion",
                   "Anhängerrangierassistent", "Rechtslenker", "Nachtsicht-Assistent",
                   "Behindertengerecht"}

mobile_car_filters = [{'Abarth': '140;;;'}, {'AC': '203;;;'}, {'Acura': '375;;;'}, {'Aiways': '31930;;;'},
                      {'Aixam': '800;;;'},
                      {'Alfa Romeo': '900;;;'}, {'ALPINA': '1100;;;'}, {'Alpine': '5;;;'}, {'Alvis': '32315;;;'},
                      {'Ariel': '31876;;;'}, {'Artega': '121;;;'}, {'Asia Motors': '1750;;;'},
                      {'Aston Martin': '1700;;;'},
                      {'Audi': '1900;;;'}, {'Austin': '2000;;;'}, {'Austin Healey': '1950;;;'},
                      {'Auto Union': '32323;;;'},
                      {'BAIC': '31863;;;'}, {'Barkas': '2600;;;'}, {'Benda': '32354;;;'}, {'Bentley': '3100;;;'},
                      {'Bizzarrini': '32316;;;'}, {'BMW': '3500;;;'}, {'Borgward': '3850;;;'},
                      {'Brilliance': '4025;;;'},
                      {'Bugatti': '4350;;;'}, {'Buick': '4400;;;'}, {'BYD': '31953;;;'}, {'Cadillac': '4700;;;'},
                      {'Casalini': '112;;;'}, {'Caterham': '5300;;;'}, {'Cenntro': '31944;;;'}, {'Chatenet': '83;;;'},
                      {'Chevrolet': '5600;;;'}, {'Chrysler': '5700;;;'}, {'Citroën': '5900;;;'}, {'Cobra': '6200;;;'},
                      {'Corvette': '6325;;;'}, {'Cupra': '3;;;'}, {'Dacia': '6600;;;'}, {'Daewoo': '6800;;;'},
                      {'Daihatsu': '7000;;;'}, {'Dallara': '32357;;;'}, {'Datsun': '30002;;;'},
                      {'Delahaye': '32317;;;'},
                      {'DeLorean': '32324;;;'}, {'DeTomaso': '7400;;;'}, {'DFSK': '31864;;;'}, {'Dodge': '7700;;;'},
                      {'Donkervoort': '255;;;'}, {'DS Automobiles': '235;;;'}, {'e.GO': '31931;;;'},
                      {'Elaris': '31932;;;'},
                      {'Estrima': '32142;;;'}, {'Facel Vega': '32318;;;'}, {'Ferrari': '8600;;;'}, {'Fiat': '8800;;;'},
                      {'Fisker': '172;;;'}, {'Ford': '9000;;;'}, {'GAC Gonow': '205;;;'}, {'Gemballa': '204;;;'},
                      {'Genesis': '270;;;'}, {'GMC': '9900;;;'}, {'Grecav': '122;;;'}, {'GWM': '30006;;;'},
                      {'Hamann': '186;;;'}, {'Heinkel': '32141;;;'}, {'Holden': '10850;;;'}, {'Honda': '11000;;;'},
                      {'Hongqi': '32228;;;'}, {'Horch': '32319;;;'}, {'Hummer': '11050;;;'}, {'Hyundai': '11600;;;'},
                      {'INEOS': '32033;;;'}, {'Infiniti': '11650;;;'}, {'Invicta': '32320;;;'}, {'Isuzu': '11900;;;'},
                      {'Iveco': '12100;;;'}, {'JAC': '30708;;;'}, {'Jaguar': '12400;;;'}, {'Jeep': '12600;;;'},
                      {'Jiayuan': '32305;;;'}, {'KGM': '32332;;;'}, {'Kia': '13200;;;'}, {'Koenigsegg': '13450;;;'},
                      {'KTM': '13900;;;'}, {'Lada': '14400;;;'}, {'Lamborghini': '14600;;;'}, {'Lancia': '14700;;;'},
                      {'Land Rover': '14800;;;'}, {'Landwind': '14845;;;'}, {'Leapmotor': '32303;;;'},
                      {'LEVC': '31933;;;'},
                      {'Lexus': '15200;;;'}, {'Ligier': '15400;;;'}, {'Lincoln': '15500;;;'}, {'Lotus': '15900;;;'},
                      {'Lucid': '32172;;;'}, {'Lynk&Co': '31934;;;'}, {'Mahindra': '16200;;;'}, {'MAN': '16500;;;'},
                      {'Maserati': '16600;;;'}, {'Maxus': '31896;;;'}, {'Maybach': '16700;;;'}, {'Mazda': '16800;;;'},
                      {'McLaren': '137;;;'}, {'Mercedes-Benz': '17200;;;'}, {'Messerschmitt': '32321;;;'},
                      {'MG': '17300;;;'},
                      {'Microcar': '30011;;;'}, {'Microlino': '32044;;;'}, {'MINI': '17500;;;'},
                      {'Mitsubishi': '17700;;;'},
                      {'Morgan': '17900;;;'}, {'NIO': '31954;;;'}, {'Nissan': '18700;;;'}, {'NSU': '18875;;;'},
                      {'Oldsmobile': '18975;;;'}, {'Opel': '19000;;;'}, {'ORA': '31955;;;'}, {'Packard': '32021;;;'},
                      {'Pagani': '149;;;'}, {'Peugeot': '19300;;;'}, {'Piaggio': '19600;;;'}, {'Plymouth': '19800;;;'},
                      {'Polestar': '4;;;'}, {'Pontiac': '20000;;;'}, {'Porsche': '20100;;;'}, {'Proton': '20200;;;'},
                      {'Renault': '20700;;;'}, {'Riley': '32322;;;'}, {'Rolls-Royce': '21600;;;'},
                      {'Rover': '21700;;;'},
                      {'Ruf': '125;;;'}, {'Saab': '21800;;;'}, {'Santana': '22000;;;'}, {'Seat': '22500;;;'},
                      {'Seres': '32144;;;'}, {'Silence': '31920;;;'}, {'Simca': '293;;;'}, {'Skoda': '22900;;;'},
                      {'Smart': '23000;;;'}, {'speedART': '188;;;'}, {'Spyker': '100;;;'}, {'Ssangyong': '23100;;;'},
                      {'Studebaker': '296;;;'}, {'Subaru': '23500;;;'}, {'Suzuki': '23600;;;'}, {'SWM': '247;;;'},
                      {'Talbot': '23800;;;'}, {'Tata': '23825;;;'}, {'TECHART': '189;;;'}, {'Tesla': '135;;;'},
                      {'Toyota': '24100;;;'}, {'Trabant': '24200;;;'}, {'Triumph': '24400;;;'}, {'TVR': '24500;;;'},
                      {'TYN-e': '32336;;;'}, {'Vincent': '31389;;;'}, {'VinFast': '32207;;;'},
                      {'Volkswagen': '25200;;;'},
                      {'Volvo': '25100;;;'}, {'Wartburg': '25300;;;'}, {'Westfield': '113;;;'}, {'WEY': '31956;;;'},
                      {'Wiesmann': '25650;;;'}, {'XEV': '32034;;;'}, {'XPENG': '32208;;;'}, {'Zeekr': '32331;;;'},
                      {'Zhidou': '32032;;;'}, {'Andere': '1400;;;'}]
